config/routes.rb
JakersRest::Application.routes.draw do

  resources :authentications

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users ,:controllers => { :registrations => 'registrations' }

  resources :rest_requests
  get "services/share_mesage"
  get "donate/index"
  get "services/index"
  get "soap/index"
  get "rest/index"
  get "home/index"
  post "rest/request_process"
  post "soap/request_process"
  post "home/sendFeedBack"
  root 'home#index'
  get '/auth/:provider/callback' => 'authentications#create'
  post '/auth/:provider/callback' => 'authentications#create'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ActionController::Base
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def index
    @authentications = current_user.authentications if current_user
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/new
  # GET /authentications/new.json
  def new
    @authentication = Authentication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/1/edit
  def edit
    @authentication = Authentication.find(params[:id])
  end

  # POST /authentications
  # POST /authentications.json
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.new(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url({:param => 'open'})
      end
    end

  end

  # PUT /authentications/1
  # PUT /authentications/1.json
  def update
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      if @authentication.update_attributes(params[:authentication])
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="field">
    <%= f.label :create %><br>
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :destroy %><br>
    <%= f.text_field :destroy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Uid</th>
      <th>Index</th>
      <th>Create</th>
      <th>Destroy</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authentications.each do |authentication| %>
      <tr>
        <td><%= authentication.user_id %></td>
        <td><%= authentication.provider %></td>
        <td><%= authentication.uid %></td>
        <td><%= authentication.index %></td>
        <td><%= authentication.create %></td>
        <td><%= authentication.destroy %></td>
        <td><%= link_to 'Show', authentication %></td>
        <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
        <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @authentication.user_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @authentication.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @authentication.uid %>
</p>

<p>
  <strong>Index:</strong>
  <%= @authentication.index %>
</p>

<p>
  <strong>Create:</strong>
  <%= @authentication.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @authentication.destroy %>
</p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>