config/routes.rb
JakersRest::Application.routes.draw do

  resources :authentications

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users ,:controllers => { :registrations => 'registrations' }

  resources :rest_requests
  get "services/share_mesage"
  get "donate/index"
  get "services/index"
  get "soap/index"
  get "rest/index"
  get "home/index"
  post "rest/request_process"
  post "soap/request_process"
  post "home/sendFeedBack"
  root 'home#index'
  get '/auth/:provider/callback' => 'authentications#create'
  post '/auth/:provider/callback' => 'authentications#create'

end

app/models/rest_request.rb
class RestRequest
  include Mongoid::Document
  include Mongoid::Timestamps


  field :user, type: String
  field :request_url, type: String
  field :request_parameters, type: String
  field :response_data, type: String
  field :response_header, type: String
  field :status, type: String
  def self.column_names
     self.fields
  end

end

app/controllers/rest_requests_controller.rb
class RestRequestsController < ApplicationController
  before_action :set_rest_request, only: [:show, :edit, :update, :destroy]

  # GET /rest_requests
  # GET /rest_requests.json
  def index
    @rest_requests = RestRequest.all
  end

  # GET /rest_requests/1
  # GET /rest_requests/1.json
  def show
  end

  # GET /rest_requests/new
  def new
    @rest_request = RestRequest.new
  end

  # GET /rest_requests/1/edit
  def edit
  end

  # POST /rest_requests
  # POST /rest_requests.json
  def create
    @rest_request = RestRequest.new(rest_request_params)

    respond_to do |format|
      if @rest_request.save
        format.html { redirect_to @rest_request, notice: 'Rest request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rest_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @rest_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rest_requests/1
  # PATCH/PUT /rest_requests/1.json
  def update
    respond_to do |format|
      if @rest_request.update(rest_request_params)
        format.html { redirect_to @rest_request, notice: 'Rest request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rest_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rest_requests/1
  # DELETE /rest_requests/1.json
  def destroy
    @rest_request.destroy
    respond_to do |format|
      format.html { redirect_to rest_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rest_request
      @rest_request = RestRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rest_request_params
      params.require(:rest_request).permit(:user, :request_url, :request_parameters, :response_data, :response_header, :status)
    end
end

app/helpers/rest_requests_helper.rb
module RestRequestsHelper
end

app/views/rest_requests/_form.html.erb
<%= form_for(@rest_request) do |f| %>
  <% if @rest_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rest_request.errors.count, "error") %> prohibited this rest_request from being saved:</h2>

      <ul>
      <% @rest_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :request_url %><br>
    <%= f.text_field :request_url %>
  </div>
  <div class="field">
    <%= f.label :request_parameters %><br>
    <%= f.text_field :request_parameters %>
  </div>
  <div class="field">
    <%= f.label :response_data %><br>
    <%= f.text_field :response_data %>
  </div>
  <div class="field">
    <%= f.label :response_header %><br>
    <%= f.text_field :response_header %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rest_requests/edit.html.erb
<h1>Editing rest_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @rest_request %> |
<%= link_to 'Back', rest_requests_path %>

app/views/rest_requests/index.html.erb
<div style="padding-top: 120px;"></div>
<div class="well col-sm-12">
<h1>Listing</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Request url</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rest_requests.each do |rest_request| %>
      <tr>
        <td><%= rest_request.user %></td>
        <td><%= rest_request.request_url %></td>
        <td><%= rest_request.status %></td>
        <td><%= link_to 'Show', rest_request %></td>
        <td><%= link_to 'Edit', edit_rest_request_path(rest_request) %></td>
        <td><%= link_to 'Destroy', rest_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rest request', new_rest_request_path %>
<div style="padding-top: 120px;"></div>
</div>

app/views/rest_requests/new.html.erb
<h1>New rest_request</h1>

<%= render 'form' %>

<%= link_to 'Back', rest_requests_path %>

app/views/rest_requests/show.html.erb
<div style="padding-top: 120px;"></div>
<p id="notice"><%= notice %></p>
<div class="col-sm-12">
  <div class="well col-sm-12">
    <div class="page-header" style="padding-bottom: 5px; margin-top:5px;">
      <h4>
        User : <%= User.find(@rest_request.user).email %>
        <br>
        <br>
        <span class="badge badge-success">
        <big><%= @rest_request.status %></big></span>&nbsp; OK
        <i class="icon-time icon-dark"></i> <small>30ms</small>
        <div class="pull-right btn-toolbar" style="margin-top: 0px">
          <div class="btn-group">
            <a class="btn-mini execute-again" tabid="#tabs-1" href="javascript: void(0);">
            <i class="icon-repeat"></i> Execute Again</a>
            <a class="btn-mini clone" tabid="#tabs-1" href="javascript: void(0);">
              <i class="icon-plus"></i>Clone Tab</a>
            <a class="btn-mini" tabid="#tabs-1" data-toggle="modal" href="#tabs-1-permalink">
              <i class="icon-share"></i> Share</a>
            <!--<a _tmplitem="2"  class="btn-mini" tabId="#tabs-1" href="javascript: void(0);"><i _tmplitem="2"  class="icon-bookmark"></i> Bookmark</a>-->
            <a class="btn-mini traceroute" tabid="#tabs-1" data-toggle="modal" href="#tabs-1-traceroute">
              <i class="icon-random"></i> Delete</a>
            <!--<a _tmplitem="2"  class="btn-mini" style="color:#f00;" tabId="#tabs-1" href="javascript: void(0);"><i _tmplitem="2"  class="icon-heart"></i> Monitor</a>-->
          </div>
        </div>
        <div style="padding-top: 10px">
          URI :  <%= @rest_request.request_url %></div>
      </h4>
    </div>

    <div class="row request-headers-section">
      <div class="col-sm-12">
        <span class="label label-info pull-left">Request Headers</span>
        <pre id="request-headers-output" class="col-sm-12">   <%= @rest_request.response_header %>      </pre>
      </div>
    </div>
    <div class="row request-parameters-section">
      <div class="col-sm-12">
        <span class="label label-info pull-left">Request Parameters</span>
        <pre id="request-parameters-output" class="col-sm-12">  <%= @rest_request.request_parameters %>      </pre>
      </div>
    </div>
    <div class="row response-headers-section">
      <div class="col-sm-12">
        <span class="label label-info pull-left">Response Headers</span>
        <pre id="response-headers-output" class="col-sm-12">  <%= @rest_request.response_header %>      </pre>
      </div>
    </div>
    <div class="row response-output-section">
      <div class="col-sm-12">
        <span class="label label-info pull-left">Response Content</span>
        <pre id="response-output" class="col-sm-12">    <%= @rest_request.response_data %>      </pre>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_rest_request_path(@rest_request) %> |
<%= link_to 'Back', rest_requests_path %>
<div style="padding-top: 120px;"></div>